[run]
init_cmds = [ ]						# Commands run in start
watch_all = true		# Watch all sub-directories
watch_dirs = [ "universe", "config", "hook" ]			# Directories to watch
watch_exts = [".go"]	# Extensions to watch
build_delay = 1500		# Minimal interval to Trigger build event
cmds = [
	["go", "test"]
]

[sync]
listen_addr = ":5050"
remote_addr = ":5050"
